[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ 
    "days/day*"
]

[dependencies]
diagonal = "0.1.0"
dotenvy = "0.15.7"
rayon = "1.10.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
