[package]
name = "day12"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "*"
aoc2024 = {path = "../../"}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
regex = "1.11.1"
diagonal = "0.1.0"
rayon = "1.10.0"
